version: "3"
services:
  postgres:
    image: postgres:12.7
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "mothership"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
