name: csid-secrets-providers
lang: java
lang_version: 17
git:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  maven_build_goals: "clean verify install dependency:analyze validate"

  tasks:
    - name: Upload to Codeartifact
      branch: main
      pipeline_file: ".semaphore/secrets-providers/publish_to_codeartifact.yml"
